[workspace]
members = [
    "mommylib",
    "apps/hello",
    "apps/ls",
    "apps/clear",
    "apps/echo",
    "apps/reboot",
    "apps/shutdown"
, "packer"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
strip = true
codegen-units = 1
